### ISSUE TITLE
[BUG] [Examples] Some of the stackblitz examples are not working

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#1545]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

```
✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.dirname
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.filename
        ╵ ~~~~~~

✘ [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.url
        ╵ ~~~~~~

failed to load config from /home/projects/wmaibgvoxb.github/vite.config.js
error when starting dev server:
Error: Build failed with 3 errors:
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
(define name):1:0: ERROR: Expected identifier but found "import"
    at failureErrorWithLog (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:1466:15)
    at eval (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:935:25)
    at runOnEndCallbacks (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:1306:45)
    at buildResponseToResult (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:933:7)
    at eval (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:960:16)
    at responseCallbacks.<computed> (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:612:9)
    at handleIncomingPacket (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:667:12)
    at Socket.readFromStdout (/home/projects/wmaibgvoxb.github/node_modules/esbuild/lib/main.js:590:7)
    at Socket.emit (node:events:30:10899)
    at addChunk (node:internal/streams/readable:225:3685)
```

it is related to:

- b2b-quote-management
- blank-playground 

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by mkucmus** [comment]
for temporary fix I recommend installing `"esbuild": "0.24.0"` in `devDependencies`.

**Comment by mkucmus** [comment]
the internal dependency of vite was upgraded and thanks to this the problem does not exist.
