### ISSUE TITLE
[BUG] Removing products from the cart doesn't work

### ISSUE THREAD

**Issue by kstala** [shopware/frontends#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Removing products added to the cart doesn't work

https://github.com/shopware/frontends/assets/30267600/4422f9a8-df0d-4616-88fb-9c4ec08b7ba9

```
entry.85e41067.js:1 ApiClientError: Failed request
 - [Not Found] Line item with identifier 65666d2629744f65b981cc6263d3ef0a not found.
    at Nk (entry.85e41067.js:32:381)
    at Object.onResponseError (entry.85e41067.js:32:1408)
    at s (entry.85e41067.js:1:89707)
    at async i (entry.85e41067.js:1:89779)
    at async u (CheckoutCartItem.vue.dd5ec403.js:1:1297)
    at async d (CheckoutCartItem.vue.dd5ec403.js:1:3201)
```

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

**Comment by BrocksiNet** [comment]
Did not see that @mdanilowicz already fixed this.
Now we have two ways of fixing it. :grin: 
You can also close my PR.
